---
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 14 days (based on index creation date)
    options:
      ignore_empty_list: True
    filters:
    - filtertype: pattern
      kind: regex
      value: '^(titan|wfm|nokia).*$'
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 14